### ISSUE TITLE
4-way allin

### ISSUE THREAD

**Issue by nguyenviettuan96** [sweeterthancandy/ps#2]
Could your code solve for four players push/ fold ? Thank you

**Comment by sweeterthancandy** [comment]
Would be possible, with infinite computation time and memory would work just by writing up the game tree, is hard coded at the moment. 
Realistically you would solve 4-player by simplifying the strategy, rather than push fold on each 169 unique card, you would both group cards together, and make each strategy uniquely described by a simple cutoff point (what s&g wizard seems to do with the percentage for each position). You would then use this to for initial guess, then actually solve the more complicated problem. This I want to do at some point
I think a more interesting problem would be to solve post-flop though.
Both are just time commitments, I'm pretty sure someone could clone with repo and solve post-flop game tree within a week as I've done all the hard code writing the efficient evaluation and figured out a way to solve a game tree
